version: '3'
services:
  backend:
    build: ./backend
    image: weatherapp_backend
    ports:
      - "9000:9000"
  frontend:
    build: ./frontend
    image: weatherapp_frontend
    ports:
      - "8000:8000"